"""Add upvotes and downvotes to alerts

Revision ID: 5daaea1723a3
Revises: af8d41dfb3b0
Create Date: 2025-04-19 14:47:00.604558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5daaea1723a3'
down_revision = 'af8d41dfb3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('downvotes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_column('downvotes')
        batch_op.drop_column('upvotes')

    # ### end Alembic commands ###
